### ISSUE TITLE
New Release?

### ISSUE THREAD

**Issue by iglesiasmarianod** [Openvario/sensord#17]
I installed stable version image today.
It still uses sensord 0.3.3 having the disconnect issues and not allowing to control volume and STF.
Do you think it might be worth it to release a new version so this bug can be fixed in the stable version too?

**Comment by linuxianer99** [comment]
@kedder: Should we release a version ?
Think we have lot of fixes..

After the release i can switch to cmake ..

**Comment by kedder** [comment]
@linuxianer99, sounds good!

**Comment by linuxianer99** [comment]
I will release without the temp sensor. It looks to me that this needs a lot of testing ...
@kedder: Agree ?

**Comment by kedder** [comment]
+1
