### ISSUE TITLE
frequent disconnects on the socket with XCSoar or variod

### ISSUE THREAD

**Issue by bomilkar** [Openvario/sensord#2]
One can observe the following symptoms:

In this configuration
sensord  --(port 4353)---> variod --(port 4352)---> XCSoar
we observer the following **error messages from variod**:

```
recv(connfd,...) return: 0
Waiting for incoming connections after 2 sentences from sensors ...
Connection accepted, reset sensor sentence counter
recv(connfd,...) return: 0
Waiting for incoming connections after 30 sentences from sensors ...
Connection accepted, reset sensor sentence counter
recv(connfd,...) return: 0
Waiting for incoming connections after 5 sentences from sensors ...
Connection accepted, reset sensor sentence counter

```
This is not always repeatable!

In this configuration
sensord  --(port 4353)---> XCSoar
we observer the following **error messages from XCSoar**:

```
Error on device TCP port 4353: End of file
Error on device TCP port 4353: End of file
Error on device TCP port 4353: End of file
Error on device TCP port 4353: End of file
Error on device TCP port 4353: End of file
Error on device TCP port 4353: End of file 
```

Also here it is not always repeatable!

**Comment by bomilkar** [comment]
After digging into `main.c` I spotted the variable sock_err in `NMEA_message_handler()` not being initialized. Since there are several paths through `NMEA_message_handler()` which don't set `sock_err `the `return(sock_err);` is **unpredictable**.
This causes the `while(sock_err >= 0)` loop in main() to end unpredictably.
**The fix is simple: initialize sock_err=0;**
This causes to error messages to stop.

The prove is: initialize to initialize sock_err-1;
This provokes the error messages continuously.

**Comment by bomilkar** [comment]
After digging a bit more in main.c I spotted one other potential issues with uninitialized data:

The `struct sockaddr_in server;` is partly undefined when `connect()` is called with this structure.
According to the documentation on connect() this may lead to unwanted behavior:
https://www.ibm.com/support/knowledgecenter/en/SSLTBW_2.1.0/com.ibm.zos.v2r1.bpxbd00/connect.htm

The lines in main.c:

```
server.sin_addr.s_addr = inet_addr("127.0.0.1");
server.sin_family = AF_INET;
server.sin_port = htons(4353);

connect()
```

The (preemptive) fix is simple:
```
// make sure the structure is in a known stat before calling connect()
memset(&server,0,sizeof(server));
server.sin_addr.s_addr = inet_addr("127.0.0.1");
server.sin_family = AF_INET;
server.sin_port = htons(4353);
```

Even if this is currently not an issue, the fix will not cause any harm.

**Comment by bomilkar** [comment]
And I spotted a third issue, which may cause unwanted delays in the execution of the main loop.

The connection on port 4353 is blocking. To the best of my understanding, this means `send()` may hang for a while if it can't deliver the data for any reason. The result would be jitter in the measure frequency. Therefor I suggest to make this connection non-blocking:

`fcntl(sock, F_SETFL, O_NONBLOCK);`

It may cause data loss. So pick your poison.

**Comment by linuxianer99** [comment]
Did you test any of these suggestions ?
Is there any change in behaviour ?

**Comment by iglesiasmarianod** [comment]
Hi guys, tested initialization but in another way.
Added sock_err=0 in the switch/case default.
```
			break;
		default:
			sock_err=0;
			break;
	}
	
	// take care for statemachine counter
	if (nmea_counter == 40)
			nmea_counter = 1;
		else
			nmea_counter++;
		
	return(sock_err);
```
It worked OK, sensord does not disconnect anymore and mute/unmute works OK.
Only this change did the trick.
Still, variod-testing is broken...
When you calibrate sensors sound "detaches" from vario. Readings are OK, but sound freezes to the last value it had. Variod_0.3.1 works OK though.
Is it possible to revert variod-testing to 0.3.1 and start over from there since all control problems were caused by this issue?
@linuxianer99 How would you like to proceed not to mix issues with Variod/Sensord?
I'll test Sensord a bit more and post a PR with the change.

**Comment by bomilkar** [comment]
Initializing `sock_err `solves the disconnects. What @iglesiasmarianod tried is equivalent since this makes sure, there isn't any more path through `NMEA_message_handler()` without setting `sock_err `before it hits `return(sock_err);` at the end.

I haven't seen any change in behavior with or without `memset(&server,0,sizeof(server));` . And I don't fully understand the effect of entering `connect()` with `struct server` partly in undefined state. But the documentation is pretty clear about what happens if you set other parts of `struct server`. Shall we leave it as is for later to debug? Or shall we put it in a defined state.

I can't try the effect of making the connection non-blocking. I have not put the system under load such that the connection is affected, and I have no sensors, hence the overall timing does not change. Making it non-blocking has no negative effect and it seems to me a reasonable thing to do.

**Comment by linuxianer99** [comment]
@iglesiasmarianod : I would prefer to fix one thing after the other. 
So, lets connect XCSoar directly to sensord (port 4353) and lets fix the disconnect issues here.
If sensord has no disconnects for about 12h long term testing, than we can go to variod issues and see what we can do here.
Feel free to provide a pull request for the `sock_err` change. I will merge and release sensord after your test are finished positive.
Sounds this resonable ??

@bomilkar : Regarding the `struct sockaddr_in` the documentation you mentioned is from IBM z/OS. So the GNU C Lib we are using has no such statement:
https://www.gnu.org/software/libc/manual/html_node/Internet-Address-Formats.html
Maybe we keep this in mind, but don't change it at the moment.

I want to avoid to change to much at one time, to get resonable test results.

**Comment by linuxianer99** [comment]
@iglesiasmarianod : i missed that there is already a PR for the sock_err. I will merge.
I still think we should do this tests mentioned above, to be sure the fix is working.

Ok for you ?

**Comment by bomilkar** [comment]
@iglesiasmarianod : it's all been said. Do what you want.

**Comment by iglesiasmarianod** [comment]
I agree. I'll build a new image with the latest changes and leave it
working at least 12 hours with only sensord connected to xcsoar.
I'll let you know the results.

**Comment by linuxianer99** [comment]
Great !
I have also build sensord with the latest changes.
Is up and running since few hours without error up to now ..

**Comment by iglesiasmarianod** [comment]
Had my OpenVario running all day yesterday with sensord connected directly to XCSoar.
Did not find any disconnections or errors in xcsoar.log.
sensord.log also seems reasonable, waiting for connections before and after XCSoar and only one or two "Send fail" in a 12 hr span.
@linuxianer99 I found issues with Variod. It does not work right from the flashing of the image.
I was thinking about opening an issue in Variod to dig into this.

**Comment by bomilkar** [comment]
@iglesiasmarianod : you haven't solved the sock_err issue entirely??
Assigning `sock_err = 0;` in the default branch is **not** enough.
There are still paths through the switch which leave sock_err undefined!
I strongly suggest to initialize at the top of the function `int sock_err = 0;`

Do you want to clean it up?

**Comment by linuxianer99** [comment]
OK, there is a possible path if no NMEA output sentence is configured.
But think that is not a problem.

Nevertheless i agree with @bomilkar that we should initialize the sock_err declaration.

@iglesiasmarianod May you please prepare a PR for that ?

**Comment by iglesiasmarianod** [comment]
Of course. I'm posting the PR now.
Please check if the change made is OK.

**Comment by bomilkar** [comment]
Looks good to me.
Thanks!

It sounds as if the other 2 (potential) issues described above are not important. So I'll close it now. Please reopen if you think we're not done, yet.
