### ISSUE TITLE
Temperature sensor and improved timing

### ISSUE THREAD

**Issue by hpmax** [Openvario/sensord#21]
I've made a few updates to my code:

1) I've cleaned up all the code.  Hopefully, Andrey will be happier with it.  All indentation is with tabs and I reduced the number of changes.
2) I am now measuring the time immediately prior to any pressure conversion.  I'm feeding the time difference between samples into the Kalman filter instead of simply putting in 50ms.  This doesn't enforce 50ms timing, but the Kalman filter update should have significantly improved accuracy.
3) Regarding the temperature sensor, I ran into some unusual behavior which I do not have an explanation for.  I am able to do a temperature conversion much faster than the DS18B20 specification says it should.  I spoke with an AE at Maxim tech support. 
 He said that conversion times should be no less than half the listed maximum time listed, but it is in my case.  He suggested it was possible I had a counterfeit part, and said if I wanted to destructively disassemble it, he could confirm whether its a legit part.  He said counterfeit DS18B20s were pretty common.

So the question is how do we handle this?  The datasheet claims 94 - 750ms conversion time depending on resolution.  Mine was about 20ms for max-resolution.  The DS18B20 can be polled for a completed conversion.  So one approach would be:

1) Initiate conversion
2) Every 12.5ms check if conversion is complete, increment counter
3) Repeat Step 2 until conversion is complete
4) Report Temperature
5) If counter < X, wait X-counter 12.5ms cycle.
6) Go back to Step 1

I'm thinking X should be between 20 and 40.  In other words, we defined a conversion rate (2-4x per second), and if the sensor can keep up, we use that speed, otherwise, we repeat the conversions as quickly as possible.  Do we define this rate in the config file?

Comments?

**Comment by hpmax** [comment]
I set up a pull request to implement these changes.  Please look it over.

**Comment by mihu-ov** [comment]
I think air temperature sensor data is not time critical and polling in 500ms or 1s cycles would be enough. Temperature data from the pressure sensors would be a different topic (polling rate causes slight temperature differences and has an impact on pressure data).

**Comment by linuxianer99** [comment]
@hpmax  Can we close this ??
