### ISSUE TITLE
voltage reported by openvario is too high

### ISSUE THREAD

**Issue by lordfolken** [Openvario/sensord#37]
The openvario reports 18.6V while the power supply reports 12,4 V.

https://user-images.githubusercontent.com/407371/145351044-5aa45aed-4df6-427d-9887-e363029df217.mp4

```bash
Build Configuration:
BB_VERSION           = "1.50.0"
BUILD_SYS            = "x86_64-linux"
NATIVELSBSTRING      = "universal"
TARGET_SYS           = "arm-ovlinux-linux-gnueabi"
MACHINE              = "openvario-57-lvds"
DISTRO               = "ovlinux"
DISTRO_VERSION       = "21343"
TUNE_FEATURES        = "arm armv7ve vfp thumb neon callconvention-hard"
TARGET_FPU           = "hard"
meta                 
meta-poky            
meta-yocto-bsp       = "HEAD:7edd2be25fdf72187738fc551235df0f24e918bb"
meta-sunxi           = "HEAD:612de90a00fbd89762e3d85d85c6846fdc1f9ef6"
meta-openvario       = "HEAD:7c349522ada91ccae88766593fe3da4af2b22b3e"
meta-oe              
meta-python          
meta-networking      = "HEAD:f72a73b42fa740130b388ba8555cdbefdee8d37d"
``` 
(I don't have a sensor board currently connected, so please ignore the vario values)

**Comment by August2111** [comment]
@linuxianer: it es possible to create a temporary `b0.3.5` branch, splitted at tag 0.3.4 from the master branch? This is only in the case, you don't like to make the tag 0.3.5 on the current state of master branch? With a rebase, unfortunately, all commit numbers in the master branch would change, a merge would literally cancel the changes made  ...
I have no idea how the review process works - and whether the changes in the master branch are not already considered reviewed? Who determines how the review process works and when such changes are classified as tested?

**Comment by linuxianer99** [comment]
Done
