### ISSUE TITLE
Sensord logs to the root parititon

### ISSUE THREAD

**Issue by lordfolken** [Openvario/sensord#40]
Sensord and Variod log to the root parition /sensord.log /variod.log 
* Log is unmanaged and will fill disc. 
* Better use standard syslogging facility, and logs will be rotated etc.

**Comment by MaxKellermann** [comment]
Workaround: https://github.com/Openvario/meta-openvario/pull/277/commits/b0adf2d609aba307b3fdfa57a7556add4eae27c4  (part of https://github.com/Openvario/meta-openvario/pull/277)

**Comment by lordfolken** [comment]
Excellent, and clever.

**Comment by linuxianer99** [comment]
Can we close this ??

**Comment by lordfolken** [comment]
i assume so.
